server {
    listen 80;
    server_name 31.97.95.53;

    location /static/ {
        alias /root/GCB-Rondoboi/app/static/;
    }

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
